portfolio pull request
Wisdomibu/Portfolio pull request #1
Opened 2023-07-31 16:43 UTC by Wisdomibu

2023-08-01 08:40 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @Wisdomibu 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ Your app matches the given design
✔️ All linters pass

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)

## Required Changes ♻️
_Check the comments under the review 👇🏽 _

- [ ] Kindly add a README file to your project and ensure you customize it. Replace the default logo with yours if you have one. You can get the approved template [here](https://github.com/microverseinc/readme-template)
- [ ] Please include a PR description to your project, it would make your project more professional

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-01 08:40 UTC, Ghiftee commented on index.html
> +    </div>
- [ ] According to the requirements, in place of `div` you are to use a `header` tag to house the logo and menu sections. You can refer to [this article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more explanation
- [ ] Kindly ensure that only the menu bar icon is inside the nav. The `nav` tag is for semantics reason and the right position for convention and user experience for mobile devices

2023-08-01 08:40 UTC, Ghiftee commented on index.html
> +        <h3>My logo</h3>
- [ ] Kindly ensure that your logo is a link, this is for three reasons: convention, semantics, and user experience(UX).

2023-08-01 08:40 UTC, Ghiftee commented on style.css
> +}
- [ ] Please, make sure you are using the right font family through out your site. It is important that as developers, we follow the given design closely

2023-08-01 08:40 UTC, Ghiftee commented on index.html
> +    </div>
- [ ] The container of this section should have a `section` tag and not a `div`. It represents a generic standalone section of the document. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2023-08-01 08:40 UTC, Ghiftee commented on index.html
> +      <h1>I'm Alex.</h1>
- [ ] For SEO reasons, it is not advisable for you to use two `<h1>` tags in this manner. To optimize your page for SEO and provide a clear structure, it is generally recommended to have only one `<h1>` tag per page, representing the main topic or title of the content.
- [ ] Additionally, please customize this section with your information.

2023-08-01 08:40 UTC, Ghiftee commented on index.html
> +      <h3>i'm a software developer</h3>
- [ ] Kindly make this `<h3>` a `p` tag. This way, it will be semantically correct and the screen readers and other technologies will thank you.

2023-08-01 08:40 UTC, Ghiftee commented on index.html
> +      </div>
- [ ] It is better to use a `ul` tag to group the list of icons, and `li` per icon; each icon has a link (`a` tag). Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.
- [ ] Also, please customize this section to have links to your social media account as this is your portfolio and not just a template

2023-08-01 08:40 UTC, Ghiftee commented on style.css
> +}
- [ ] As it is a part of the design, please add the highlighted section in the image below to your own design and ensure you use the right spacing for all elements throughout your website.
![Screenshot 2023-08-01 at 09 31 45 (2)](https://github.com/Wisdomibu/Portfolio/assets/64774936/1530fd81-a966-4fb4-9454-b8d76abce204)

2023-08-01 16:59 UTC, Wisdomibu commented
I implemented all the corrections from the earlier review

2023-08-04 08:41 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @Wisdomibu, 

Your project is complete!  There is nothing else to say other than... It's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/749155b89333c6d89386f5c98dd110e234a00f2aa1e864a5b3fecaf089aedb27/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f36664a31424d375232454252446e784b2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

2023-08-04 09:15 UTC, merged